from enum import Enum

class CrucialSkill(Enum):
    MINING = 1
    WOODCUTTING = 2
    CARPENTRY = 3
    MASONRY = 4
    FORGE_WEAPON = 5
    BOWYER = 6
    FORGE_ARMOR = 7
    FORGE_FURNITURE = 8
    SMELT = 9
    WOOD_BURNING = 10
    FISH = 11
    BUTCHER = 12
    PLANT = 13
    BREWING = 14
    CUTGEM = 15
    ENCRUSTGEM = 16
    CUT_STONE = 17
    CARVE_STONE = 18
    ENGRAVE_STONE = 19
    METALCRAFT = 20
    STONECRAFT = 21
    WOODCRAFT = 22
    BONECARVE = 23