from enum import Enum

class LaborSkill(Enum):
    MECHANICS = 1
    POTTERY = 2
    GLAZING = 3
    PAPERMAKING = 4
    BOOKBINDING = 5
    WAX_WORKING = 6
    MILLING = 7
    PROCESSPLANTS = 8
    HERBALISM = 9
    COOK = 10
    WEAVING = 11
    CLOTHESMAKING = 12
    DYER = 13
    TRAPPING = 14
    SNEAK = 15
    TANNER = 16
    LEATHERWORK = 17
    DISSECT_FISH = 18
    DISSECT_VERMIN = 19
    PROCESSFISH = 20
    CHEESEMAKING = 21
    MILK = 22
    GELD = 23
    SHEARING = 24
    SPINNING = 25
    PRESSING = 26
    BEEKEEPING = 27
    ANIMALTRAIN = 28
    ANIMALCARE = 29
    SOAP_MAKING = 30
    LYE_MAKING = 31
    POTASH_MAKING = 32
    GLASSMAKER = 33
    OPERATE_PUMP = 34
